### ISSUE TITLE
【疑似被ban了】部署报错，麻烦大佬看下，感谢

### ISSUE THREAD

**Issue by fengjunren** [gaboolic/vercel-reverse-fast#34]
![2023-09-15_115309](https://github.com/gaboolic/vercel-reverse-proxy/assets/18107765/1c71ed08-ecc6-42f0-825e-92dae77d51f8)

**Comment by gaboolic** [comment]
日了狗了，我试了一下报错This content violates Vercel's Terms of Service, and/or rules on Fair Use.
你看看报错是这个不

**Comment by gaboolic** [comment]
你复制到你自己的仓库 删掉readme 改改项目名啥的试试吧。如果还不行就是被彻底ban了

**Comment by kokojacket** [comment]
是已经没了吗？

**Comment by JerryXu09** [comment]
我部署的至今可用

**Comment by happy4first** [comment]
自己参照楼主弄了一个，可以布了：https://github.com/happy4first/vp

**Comment by gaboolic** [comment]
> 是已经没了吗？

我自己的仓库被ban了
你别fork，新建，复制，应该是没问题的
