### ISSUE TITLE
不支持的国家/地区/地区

### ISSUE THREAD

**Issue by donnykey** [gaboolic/vercel-reverse-fast#49]
vercel 好像不行了，提示不支持的地区；
{"error":{"code":"unsupported_country_region_territory","message":"Country, region, or territory not supported","param":null,"type":"request_forbidden"}}

{“错误”：{“代码”：“不支持的国家/地区/地区”，“消息”：“国家/地区、地区或地区不受支持”，“参数”：null，“类型”：“request_forbidden”}
，怎么自荐vps节点部署呢

**Comment by gaboolic** [comment]
换ip注册
