### ISSUE TITLE
Response with random text

### ISSUE THREAD

**Issue by VladLikov** [gaboolic/vercel-reverse-fast#52]
Hello, 

I used it my own iOS App with ChatGPT. It's start response well like few sentences and then response random sentences (like on screenshot below). Can you help me? With raw Open AI API everything working well.

![IMG_4495](https://github.com/user-attachments/assets/2725b5c9-27f6-4ab8-b8cf-c10a4b0cdfb6)
![IMG_4496](https://github.com/user-attachments/assets/d07f6e3e-fe79-4afc-97f5-87369cdff271)

**Comment by gaboolic** [comment]
You can copy the HTTP body, and then paste it into a tool like PostMan to test it.
Theoretically, this proxy project does not change the HTTP packet.
